gh-22: Added MIT LICENSE
99xt/youtube-fullscreen-playlist pull request #25
Opened 2017-08-18 08:18 UTC by dinukadesilva

this closes #22

2017-08-22 03:32 UTC, rehrumesh commented on LICENSE
> +Copyright (c) 2017 99XT
Copyright should be for 99X Technology

2017-08-22 03:33 UTC, rehrumesh requested changes
Copyright should be for 99X Technology

2017-08-22 03:33 UTC, rehrumesh commented
@dinukadesilva Please check the comments.

2017-08-22 06:07 UTC, dinukadesilva commented
Done

2017-08-25 17:16 UTC, rehrumesh commented
@dinukadesilva Thanks 🥇

2017-08-25 17:16 UTC, merged