Fixes: #16 - Added a issue template and Pull request templates
99xt/youtube-fullscreen-playlist pull request #27
Opened 2017-08-21 04:05 UTC by isuruAb

Added  Issue template and Pull Request template

2017-08-21 07:40 UTC, dinukadesilva requested changes

2017-08-21 07:40 UTC, dinukadesilva commented on .github/PULL_REQUEST_TEMPLATE
> +Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Few suggestions,

**Branch name**
`gh-`<--related issue number-->

eg: `gh-34`

**Commit message title**
`gh-`<--related issue number-->: <--commit title-->

eg: `gh-34: Updated variable names`

**Commit message description**
fixes <--issue number-->
closes <--issue number-->
etc.

**Pull request title**
<--branch-name-->: <--pull request title-->

2017-08-21 07:48 UTC, dinukadesilva commented
@isuruAb 
Create links to these files from readme.
https://github.com/99xt/youtube-queuing-bot/issues/3 can be taken as a part of this PR

2017-08-22 03:37 UTC, rehrumesh commented on .github/PULL_REQUEST_TEMPLATE
> +Fixes issue #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Good suggestion. However we don't follow specific rules for branching. Contributors are free to use their own format. However commit message should start with `#issue_id <description>`

2017-08-22 03:37 UTC, merged

2017-08-22 12:43 UTC, dinukadesilva commented
This is nice. It reminded me to add demo links too.

![image](https://user-images.githubusercontent.com/10680296/29565909-85196fb2-8765-11e7-980c-cb09b1d7b22d.png)

2017-08-22 12:43 UTC, dinukadesilva commented
How about having the titles bold.